# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = zbuffer_qt
DEFINES += _WINDOWS QT_LARGEFILE_SUPPORT QT_DLL
INCLUDEPATH += . \
    $(QTDIR)/mkspecs/win32-msvc2008
DEPENDPATH += .
UI_DIR += ./GeneratedFiles
include(zbuffer_qt.pri)